### ISSUE TITLE
Error on mvn install

### ISSUE THREAD

**Issue by lbineau** [SadyRifat/aem-vue#1]
I'd like to test your example to see how it behave with authoring.
I've got the following error when executing `mvn install`, any idea why?
```bash
[ERROR] Failed to execute goal on project aem-vue.ui.apps: Could not resolve dependencies for project com.aem.vue:aem-vue.ui.apps:content-package:0.0.1-SNAPSHOT: Could not find artifact com.aem.vue:aem-vue.ui.frontend:zip:0.0.1-SNAPSHOT -> [Help 1]
```

Thank you.

**Comment by mohamedchaabani** [comment]
Hello, me too i just clone the projet and i got the same error!
can you please tell us if we are missing something ?
thanks

**Comment by SadyRifat** [comment]
Hello, I will get back to you tomorrow with a solution.
In the meantime I will do a test run in other PC.

**Comment by mohamedchaabani** [comment]
Hi, it's me again :) 
i just have a technical question please.
in your example you are explaning that all vue Js componenet will be on the app.bundle.js  as a client lib that i can use on my AEM components.
but suppose that i have developed a 100 vue js components so the final file app.bundle.js will be very hudge and i m obliged to used it on all my web site even there is an AEM page which use only 1% of this file.
i want to know is there a way please to have many clientlibs.
vuejs component 1 will have cmp1.buil.js
vuejs component2 will have cmp2.build.js 
and i can use only the client lib that i need on my aem component ?
thanks for your response in advance

**Comment by SadyRifat** [comment]
Hello @mohamedchaabani.
Yes, it is a valid concern and that's why initially I set up with fe-build tool instead of webpack. But unfortunately, Vue doesn't work like that. `const app = createApp` pull all the registered components and mounts on an ID.

**Comment by SadyRifat** [comment]
This issue is resolved in the last commit. However, I got another complain regarding fe-build setup.
You can also check `webpack-build-with-typescriptcom` which usages `webpack`
Thank you.

**Comment by SadyRifat** [comment]
This issue is resolved in the last commit. However, I got another complain regarding fe-build setup.
You can also check webpack-build-with-typescriptcom which usages webpack
